SELECT 
     [Policy_ID]
      ,[POL_PolicyNumber]
      ,[WW_Policy_Key]
      ,[ProductClass]
      ,FORMAT(cast([POL_OriginalStartDate] AS DATE), 'dd-MMM-yyyy') as [POL_OriginalStartDate] 
      ,FORMAT(cast([StartMonth] AS DATE), 'dd-MMM-yyyy') as [StartMonth]
      ,FORMAT(cast([ValuationMonth] AS DATE), 'dd-MMM-yyyy') as [ValuationMonth]
      ,[ElapsedMonths]
      ,FORMAT(cast([Pol_SoldDate] AS DATE), 'dd-MMM-yyyy') as [Pol_SoldDate]
      ,FORMAT(cast([POL_EndDate] AS DATE), 'dd-MMM-yyyy') as [POL_EndDate]
      ,[Product_Level1]
      ,[Product_Level2]
      ,[Product_Level3]
      ,[CellCaptive]
      ,[INS_InsurerName]
      ,[Term]
      ,[PhasingCurve]
      ,[Agt_Name]
      ,ISNULL([EarnedPortion],0) AS [EarnedPortion]
      ,ISNULL([UnearnedPortion] ,0) AS [UnearnedPortion]
      ,ISNULL([WW_Nett_Premium] ,0) AS [WW_Nett_Premium]
      ,ISNULL([WW_Nett_Fund] ,0) AS [WW_Nett_Fund]
      --,ISNULL([WW_Nett_Binder] ,0) AS [WW_Nett_Binder]
      ,ISNULL([WW_Nett_Commission] ,0) AS [WW_Nett_Commission] 
     -- ,ISNULL([WW_Roadside] ,0) AS [WW_Roadside]
      ,ISNULL([WW_IsMigrated] ,0) AS [WW_IsMigrated]
      ,ISNULL([Evolve_Nett_Premium] ,0) AS [Evolve_Nett_Premium]
      ,ISNULL([Evolve_Nett_Fund] ,0) AS [Evolve_Nett_Fund]
     -- ,ISNULL([Evolve_Nett_Binder] ,0) AS [Evolve_Nett_Binder]
      ,ISNULL([Evolve_Nett_Commission] ,0) AS [Evolve_Nett_Commission]
      ,ISNULL([UPP] ,0) AS [UPP] 
      ,ISNULL([DAC] ,0) AS [DAC] 
  , FORMAT(cast([POL_CreateDate] AS DATE), 'dd-MMM-yyyy') as [POL_CreateDate]
      ,ISNULL([DAC_Out] ,0) AS [DAC_Out]
      ,ISNULL([DAC_Acq],0) AS [DAC_Acq]
      ,ISNULL([DAC_Binder_Claims] ,0) AS [DAC_Binder_Claims]
      ,ISNULL([DAC_Underwriter],0) AS [DAC_Underwriter]
      ,ISNULL(FORMAT(cast([PMI_RegistrationDate] AS DATE), 'dd-MMM-yyyy'),'') as [RegistrationDate] 
  FROM [UPP].[dbo].[SAW_UPP_202510]
  where 1 = 1 
  and INS_InsurerName = 'Centriq Short Term'
